### ISSUE TITLE
评论：安装 Node 和 gulp

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#10]
请在此处留下你对 [安装 Node 和 gulp](https://github.com/nimojs/gulp-book/blob/master/chapter1.md) 的评论

**Comment by zhishan33** [comment]
node 4.3 安装gulp 要求升级graceful-fs和lodash 模块。怎么升级这俩个模块

**Comment by sk-blog** [comment]
graceful-fs和lodash 模块,怎么升级这俩个模块,npm老提示这个~~

**Comment by mishengqiang** [comment]
@zhishan33 @avilang 这不是nodejs的问题时gulp的问题，gulp官方说4.x版本解决，3.x版本就这样了。https://github.com/gulpjs/gulp/issues/1587
