### ISSUE TITLE
评论：使用 gulp 压缩 CSS

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#12]
请在此处留下你对 [使用 gulp 压缩 CSS](https://github.com/nimojs/gulp-book/blob/master/chapter3.md) 的评论

**Comment by xiaohp** [comment]
> 你可以访问 [gulp-minify-css](https://github.com/jonathanepollack/gulp-minify-css) 以查看更多用法。

这个链接打不开

**Comment by xiaoniudadi** [comment]
现在的话gulp-minify-css是已经被舍弃掉了，现在都是gulp-clean-css，这个也挺好都用的。[gulp-clean-css](https://github.com/scniro/gulp-clean-css)

**Comment by xiaohp** [comment]
好的，感谢告知。

**Comment by shujiabi** [comment]
我跟着操作  但最后没有压缩成功  是复制了一个css文件夹出来

**Comment by postbird** [comment]
@shujiabi 你的task怎么写的？使用的是 `gulp-clean-css` ? 

https://www.npmjs.com/package/gulp-clean-css

```javascript
let gulp = require('gulp');
let cleanCSS = require('gulp-clean-css');
let sourcemaps = require('gulp-sourcemaps');
 
gulp.task('minify-css',() => {
  return gulp.src('./src/*.css')
    .pipe(sourcemaps.init())
    .pipe(cleanCSS())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('dist'));
});
```
