### ISSUE TITLE
评论：使用 gulp 编译 LESS

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#14]
请在此处留下你对 [使用 gulp 编译 LESS](https://github.com/nimojs/gulp-book/blob/master/chapter5.md) 的评论

**Comment by liangguoer** [comment]
问题很多，我一开始偷懒直接copy了你的文件，但是各种报错，最后还是我手动修改

**Comment by nimojs** [comment]
刚下载后 `gulp 3.9.1` 构建了一遍没发现报错。你的报错信息是什么。修改了什么导致不报错的？
