### ISSUE TITLE
评论：使用 gulp 编译 Sass

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#15]
请在此处留下你对 [使用 gulp 编译 Sass](https://github.com/nimojs/gulp-book/blob/master/chapter6.md) 的评论

**Comment by a958330481** [comment]
按照如上说明去配置gulp sass(gulp-ruby-sass版本号：2.0.0)，执行时出现下面错误信息：

    Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (F:\gulp\node_modules\gulp-ruby-sass\logger.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

求解？

**Comment by nimojs** [comment]
请先试试
```
npm install gulp-ruby-sass@1.0.1
```

**Comment by uooo** [comment]
目前在使用gulp-sass编译scss文件

**Comment by nimojs** [comment]
恩，gulp-sass 比gulp-ruby-sass 要快。gulp-ruby-sass 是用ruby编译的，功能要全。

**Comment by uooo** [comment]
主要原因是 gulp-sass 不用装 ruby，但是，依赖包 node-sass 在国内下载经常失败

**Comment by a958330481** [comment]
@uooo 关于gulp-sass与gulp-ruby-sass对比的文章,推荐看下这篇：
http://segmentfault.com/a/1190000003112509

**Comment by a958330481** [comment]
@nimojs 谢谢~ 我换成了用gulp-sass;已经解决问题，现在改用你的建议重新试下

**Comment by uooo** [comment]
gulp-sass 依赖底层的 c++ 构建的二进制文件，可以通过在本地设置环境变量缓存，这样就不用重新下载。具体参考 node-sass 的github

**Comment by nimojs** [comment]
ruby sass 坑还是挺大的，周末我还是要把教程中的 gulp-ruby-sass 换成 gulp-sass

**Comment by a958330481** [comment]
换成 gulp-ruby-sass@1.0.1 之后,运行变得正常，那个错误应该是由于gulp-ruby-sass版本不同引起的

**Comment by uooo** [comment]
目前 gulp-sass 相对来说已经可用了，可以尝试尝试

**Comment by ivvvy** [comment]
无法显示task如图所示该怎么解决！
![qq 20160121125635](https://cloud.githubusercontent.com/assets/12122418/12472062/2426c266-c03f-11e5-90fe-233cd049e916.png)

**Comment by nimojs** [comment]
@ivvvy 目测 node-sass npm install 时没有编译成功

跟 node 版本有关系，我同事经常遇到这个问题。最后只能换 node 版本解决。

**Comment by luqin** [comment]
[node-sass 安装失败解决方案](https://github.com/luqin/blog/issues/9)，
在公司我是搭了一个 node-sass 下载包代理服务器，
不过没有在文档补充，相信对于大家来说是小菜一碟。

**Comment by ivvvy** [comment]
@nimojs 我要重新再装吗

**Comment by nimojs** [comment]
@ivvvy 这是个坑，我同事解决这个问题都是一次一次的换版本重装。

**Comment by ivvvy** [comment]
@nimojs 啊这样啊 没有一次性解决的办法嘛

**Comment by ivvvy** [comment]
@nimojs 这。。。
