### ISSUE TITLE
评论：使用 gulp 构建一个项目

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#16]
请在此处留下你对 [使用 gulp 构建一个项目](https://github.com/nimojs/gulp-book/blob/master/chapter7.md) 的评论

**Comment by Gaohaoyang** [comment]
为什么不用严格模式？
每一行后面都没有分号，看着好难受

**Comment by Softor** [comment]
为什么在贴出的 package.json 的内容里么有出现 gulp-util ?

**Comment by nimojs** [comment]
https://github.com/nimojs/gulp-demo/

第七章最终代码在
https://github.com/nimojs/gulp-demo/blob/master/package.json#L17

**Comment by lengziyu** [comment]
你好，我用了你的gulp-demo ，然后gulp命名后，打开什么地址预览？

**Comment by nimojs** [comment]
@lengziyu 
在 https://github.com/nimojs/gulp-demo/tree/master/html 中直接打开 HTML 文件预览，

**Comment by junhey** [comment]
可以报所有的npm install全部写出来，便于安装

安装插件
npm install gulp-util gulp-uplify gulp-watch-path stream-combiner2 gulp-sourcemaps gulp-minify-css gulp-autoprefixer gulp-less gulp-ruby-sass gulp-imagemin gulp-handlebars gulp-wrap gulp-declare

**Comment by jillsGit** [comment]
sass部分貌似不行

**Comment by chongyuan** [comment]
安装gulp-uglify等依赖之后，package.json的devDependencies并没有更新，是我哪里操作有误吗？

**Comment by nimojs** [comment]
@chongyuan 
```
–save：模块名将被添加到dependencies，可以简化为参数-S。
–save-dev: 模块名将被添加到devDependencies，可以简化为参数-D。
```

**Comment by stevenlvcrow** [comment]
既然会把代码压缩，那么在index的引入代码也要相应变化。这块该怎么写

**Comment by nimojs** [comment]
@stevenlvcrow 什么意思
是指  index.html 中引入路径要自动变成 dist/a.js ?

**Comment by yzren** [comment]
您好，我想请问一下，为什么sass编译不成功

**Comment by nimojs** [comment]
@yzren 报错信息 node版本 gulp 版本 插件版本发一下

**Comment by yzren** [comment]
node :3.8.9
gulp :3.9.1

不报任何错误信息，没有反应，编译不出来，less和css 还有js都是没有问题的。谢谢啦

**Comment by yzren** [comment]
![qq 20160824182323](https://cloud.githubusercontent.com/assets/15935252/17927375/f7189856-6a27-11e6-806e-ceeb8724f39f.png)

**Comment by nimojs** [comment]
@yzren 如果一直卡主可能是 sass 编译速度慢的原因，否则会报错。

**Comment by luuman** [comment]
不是有自动刷新的插件吗？

**Comment by seed-fe** [comment]
使用stream-combiner2输出错误信息的时候遇到lineNumber: undefined，错误信息也只有：unable to minify javascript，没有详细的错误信息，请问这可能是什么原因啊？

**Comment by nimojs** [comment]
@seed-fe  可以试着一行行删除要压缩的JS源码排查是哪一行无法亚索

**Comment by seed-fe** [comment]
@nimojs 我把gulp-uglify换成低版本的就好了
