### ISSUE TITLE
第7章链接去掉

### ISSUE THREAD

**Issue by 2319103827** [nimojs/gulp-book#24]
https://github.com/nimojs/gulp-book/blob/master/chapter7.md

colors 模块去掉

**Comment by zchen9** [comment]
第七章配置js任务的输出路径写成css了

**Comment by nimojs** [comment]
@zchen9  麻烦指出详细文字区域

**Comment by zchen9** [comment]
![image](https://cloud.githubusercontent.com/assets/11719888/8142947/5ce9f2a4-11c5-11e5-95bd-bce53d27845f.jpg)

**Comment by nimojs** [comment]
非常感谢
