### ISSUE TITLE
使用 gulp 实现兼容 seajs 和 requirejs 的打包工具

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#25]
**基本思路：**

```
gulp.src('src/js/page/a.js')
       .pipe(build())
       .pipe(gulp.dest())
```

```
// src/js/page/a.js
seajs.use(['jquery',
    'arale/tip/1.2.2/tip',
    'rain/daterange/0.0.1/daterange',
    'gallery/webuploader/0.1.5/webuploader',
    'arale/validator/0.9.7/validator',
    'arale/dialog/1.3.0/dialog'
    ],
    function (a,b,c,d) {
// .. code  ... 
})
```

---- 以上代码会编译成 ------

```
// dist/js/page/a.js
(function(){
defined('jquery/1.0.1/jquery')....
defined('arale/tip/1.2.2/tip')....
defined('arale/dialog/1.3.0/dialog')...
// ... code ...

})()
```

参考的 spm3 实时开发方式

**Comment by nimojs** [comment]
spm 3.6 能很好地应对各种类型的开发需求，不需要重复造轮子。（而spmjs.io 提供了生态系统）

**Comment by lichunqiang** [comment]
求分享

**Comment by nimojs** [comment]
@lichunqiang  
spm 教程就是你 star 过的这个项目 https://github.com/spmjs/docs

使用spmjs.io 已有的模块进行开发时非常方便，方便程度与用 npm 差不多了。

如果 spmjs.io 没有某些模块需要自己 spm publish 

-----

我们团队目前对于模块化开发的解决方案是：
不特别在意 HTTP请求数的使用 服务器在线 combo [请参考这个项目](https://github.com/nimojs/seajs-cmd)
在意 HTTP请求数的使用 spmv3.6 本地打包

**Comment by nimojs** [comment]
其实 seajs 和 spm 的主要贡献者们多次提到过：
> spm3已经完全与seajs脱离关系了。某种程度上与 seajs 无任何关系。

可以在seajs 的github社区上看到，关于打包的问题一直有。也一直没有方便的解决方案。

- 需要手动封装模块为 cmd
- 需要各种 grunt gulp 的配置
- 使用停止维护的spm2 进行打包

都因为 cmd 规范的原因有各种痛点。

而spm3直接基于 CommonJS 开发模块，提供了类似 npm 的 publish install 功能。当生态环境积累的够强大的时候，真的是无痛开发。
