### ISSUE TITLE
安装gulp 记得提示用户 sudo

### ISSUE THREAD

**Issue by Yunkou** [nimojs/gulp-book#29]
哥们你的文章在Google排行权重很高，相信很多人看，其中会有小白，可能没有 `sudo` 安装失败，对小白造成困扰哦。

**Comment by nimojs** [comment]
https://github.com/nimojs/gulp-book/blob/master/chapter1.md#安装-gulp

> 如果你安装失败，请输入sudo npm install -g gulp使用管理员权限安装。（可能会要求输入密码）

恩，这里有提示
