### ISSUE TITLE
sass编译不出来

### ISSUE THREAD

**Issue by OliveKong** [nimojs/gulp-book#37]
![image](https://cloud.githubusercontent.com/assets/7875818/20166957/1ee86ccc-a753-11e6-802e-28eabd2209a7.png)
不报错，可是文件夹中没有编译好的sass文件

**Comment by wuyanwen** [comment]
把代码粘贴上来看下

**Comment by OliveKong** [comment]
现在好了，我改了下gulp-ruby-sass的版本，就可以了，谢了！

**Comment by OliveKong** [comment]
gulp是不是还有很多方法，我看你最后的项目中配置的gulpfile.js中，有很多写法是前面的demo中没有的，请问有没有学习gulp的网站啥的，给我推荐下吧，谢谢！

**Comment by nimojs** [comment]
https://github.com/lisposter/gulp-docs-zh-cn
@OliveKong 

看API文档是一方面。另外一方面是看一些不错项目的 gulpfile.js ，因为里面总能找到很多奇淫巧技。

关键是你要有构建的思路。API反正就那么点。

**Comment by OliveKong** [comment]
好的，谢谢！
