### ISSUE TITLE
订阅本书

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#7]
## 邮件订阅
[点击此处](http://www.mikecrm.com/f.php?t=YGV8i4)邮件订阅
<img src="https://cloud.githubusercontent.com/assets/3949015/6850719/bf6f642e-d415-11e4-8096-157ed60f3c3b.png" width="300">
## Github 订阅
点击本页面右上角的 [Watch](https://github.com/nimojs/gulp-book/subscription)  在弹出框中点击 `Watching` 订阅本博客，这样本书的所有更新和讨论都会在github首页出现。
![image](https://cloud.githubusercontent.com/assets/3949015/6850925/f12bc470-d416-11e4-9a09-ec3f59041a00.png)
## 收藏
点击 `Star` 收藏本书，以便在 [stars](https://github.com/stars) 中找到本博客。

**Comment by ailenHuang** [comment]
不错！  真心不错！我学习！

**Comment by kokokele** [comment]
赞!!!!

**Comment by Leon905873832** [comment]
你好，那个错误处理函数handleError哪里，error.lineNumber的值是undefined，这个是不是不对

**Comment by nimojs** [comment]
@Leon905873832  打印一下 error的完整信息，根据完整信息看是不是返回的错误信息
