### ISSUE TITLE
评论交流

### ISSUE THREAD

**Issue by nimojs** [nimojs/gulp-book#8]

**Comment by amibug** [comment]
希望楼主更新一个gup 用gulp-useref或者gulp-usemin，整合requirejs的项目，用gulp来打包构建requirejs加载js的项目

**Comment by nimojs** [comment]
@amibug 
我平时是使用 seajs ，通过服务器 combo 自动合并模块。[seajs-cmd](https://github.com/nimojs/seajs-cmd) [使用 seajs-combo 合并请求](http://cmd.nimojs.com/examples/arale-dialog-combo.html)

你可以加我QQ： 2049658509 我们一起探讨一下 requirejs 如何打包。

**Comment by lichunqiang** [comment]
那就出一集 [gulp-useref](https://github.com/jonkemp/gulp-useref) 吧 :+1:

**Comment by nimojs** [comment]
@amibug  @lichunqiang 
关于模块化开发的打包我觉得自己实现一个 gulp 插件比较靠谱。
新开了一个 issues https://github.com/nimojs/gulp-book/issues/25  二位觉得是否使用方便可行

**Comment by amibug** [comment]
:+1:先用着看看

**Comment by 2319103827** [comment]
我想了解如何使用 gulp 将 retina 图片自动改为1倍尺寸和2倍尺寸

**Comment by nimojs** [comment]
@amibug  @lichunqiang 关于本地打包推荐使用 [spm](https://github.com/spmjs/docs) 来解决问题。

一整套的集成解决方案能很好的解决问题，准备等spm升级后的新Bug修复后使用 gulp 调 spm 的api来打包 CommonJs

**Comment by tcstory** [comment]
**stream-combiner2** 并不会在报错的时候继续编译代码吧?我测试了好多次都是这样的

**Comment by nimojs** [comment]
@tcstory 
是的 他会拦截错误，并将错误输出，但不会中断代码监听

**Comment by heyxiaoling** [comment]
我想了解gulp和require.js的打包问题，谢谢



1186608119@qq.com
 
发件人： Nimo Chu
发送时间： 2015-08-09 09:01
收件人： nimojs/gulp-book
主题： Re: [gulp-book] 在此留下你想了解的 gulp 知识，提醒我们更新 (#8)
@tcstory 
是的 他会拦截错误，并将错误输出，但不会中断代码监听

**Comment by imanhuaa** [comment]
完整的本地开发环境，包括测试， local server

**Comment by nimojs** [comment]
@imanhuaa  每个项目需要配置的环境不一样，基本上按照第七章的内容做增加修改就可以根据业务场景配置出来，server 可以试试 [FMS](http://fms.help/) Front-end Mock Server (模拟AJAX模拟,后端模板引擎渲染)

**Comment by ailenHuang** [comment]
有没有关于  压缩typescript的教程，压缩.ts文件

**Comment by nimojs** [comment]
@ailenHuang 
```js
var gulp = require('gulp');
var ts = require('gulp-typescript');

gulp.task('default', function () {
    return gulp.src('src/**/*.ts')
        .pipe(ts({
            noImplicitAny: true,
            out: 'output.js'
        }))
        .pipe(gulp.dest('built/local'));
});
```

https://github.com/ivogabe/gulp-typescript

这个试过吗

**Comment by ailenHuang** [comment]
gulp-typescript
如何捕获error事件;
我用gulp.watch  出现错误就断了;
noEmitOnError  用这个参数不输出错误信息也不行

**Comment by nimojs** [comment]
@ailenHuang 
https://github.com/nimojs/gulp-book/blob/master/chapter7.md#stream-combiner2
> 编辑 log.js 文件时，如果文件中有 js 语法错误时，gulp 会终止运行并报错。
应对这种情况，我们可以使用 Combining streams to handle errors 文档中推荐的 [stream-combiner2](https://github.com/substack/stream-combiner2) 捕获错误信息。

**Comment by yufeisky** [comment]
＠nimojs 　你好，我想了解给image路径加md5戳的时候，具体怎样处理的，还有在css跟js里面的图片路径怎样才能同步也修改

**Comment by nimojs** [comment]
@yufeisky 
这是个大坑我以前也想用 gulp 解决，你先看看这篇文章

https://github.com/fouber/blog/issues/5 资源定位中md5戳的计算过程

gulp处理这种 md5『联动修改』**很麻烦**。 

在几个月前我把构建工具从 gulp 换成了 fis, fis内置支持这个功能不需要额外配置. http://fis.baidu.com/fis3/docs/beginning/release.html#%E6%96%87%E4%BB%B6%E6%8C%87%E7%BA%B9

**Comment by yufeisky** [comment]
@nimojs　嗯　感谢你的回复，　我也有看到 fis3我有看到这方面的功能，
![fis3](https://cloud.githubusercontent.com/assets/4506632/11523450/5334718e-98fd-11e5-9079-4bfcaac2c9d8.png)

fis.match('*.{js,css,png}', {
  useHash: true
});

// 启用 fis-spriter-csssprites 插件
fis.match('::package', {
  spriter: fis.plugin('csssprites')
})

// 对 CSS 进行图片合并
fis.match('*.css', {
  // 给匹配到的文件分配属性 `useSprite`
  useSprite: true
});

fis.match('*.js', {
  // fis-optimizer-uglify-js 插件进行压缩，已内置
  optimizer: fis.plugin('uglify-js'),
   release: 'html/yufei-file/201511before/fis3/out/js/'
});

fis.match('*.css', {
  // fis-optimizer-clean-css 插件进行压缩，已内置
  optimizer: fis.plugin('clean-css'),
   release: 'html/yufei-file/201511before/fis3/out/css/'
});

fis.match('*.png', {
  // fis-optimizer-png-compressor 插件进行压缩，已内置
  optimizer: fis.plugin('png-compressor'),
  release: 'html/yufei-file/201511before/fis3/out/images/'
})
想请教下fis3用绝对路径，该怎么配置发布路径， release: 'html/yufei-file/201511before/fis3/out/js/'我这样设置　然后启动 fis3 release -d ../output  它会在out下面生成一个 release配置中的路径文件夹
html/yufei-file/201511before/fis3/out/js/

**Comment by yufeisky** [comment]
@nimojs
![fis33](https://cloud.githubusercontent.com/assets/4506632/11523591/76a86ac0-98fe-11e5-8e8d-8ae884bbe699.png)
在output下面生成了这个文件夹

**Comment by nimojs** [comment]
建议你看看这里的文档 http://fis.baidu.com/fis3/docs/beginning/release.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

如果你使用了 md5 这个功能，那么你根本就不需要 配置 `201511before` 这样的 `release` 路径

因为[文件指纹](http://fis.baidu.com/fis3/docs/beginning/release.html#%E6%96%87%E4%BB%B6%E6%8C%87%E7%BA%B9) 的作用就是要合理利用缓存，如果你每次都发布一个新文件夹就不需要用文件指纹

**Comment by yufeisky** [comment]
@nimojs　哈　再次感谢，听你说了之后又翻查了一下fis3的文档　有一个配置url的参数

**Comment by yufeisky** [comment]
比方说我想发布到http:192.168.1.1/app/201520151202/这个目录下 要是不配置路径fis3 是自动发布到http:192.168.1.1/这个下面,不过受你启发　好像知道怎么该了　我先去尝试下　再次感谢

**Comment by yufeisky** [comment]
@nimojs　
![fis333](https://cloud.githubusercontent.com/assets/4506632/11524045/59748930-9902-11e5-864a-5f1448406e98.png)
我这样配置了url之后就可以定义到对应路径了
![fis5](https://cloud.githubusercontent.com/assets/4506632/11524142/18a654aa-9903-11e5-8ea3-2f557bcc2be4.png)

**Comment by freedomdebug** [comment]
[16:21:26] Using gulpfile E:\mywork\gulpdemo\gulpfile.js
[16:21:26] Starting 'sasscss'...
[16:21:26] Finished 'sasscss' after 80 ms
[16:21:26] 'sass' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���                                                                                                                                                                                                                                                                                                                   
���������ļ���
Error! Gem undefined is not installed.

**Comment by nimojs** [comment]
提供的报错信息不完全，`[16:21:26] 'sass' ` 都是乱码

@freedomdebug 
估计是 ruby-sass 原因

https://github.com/nimojs/gulp-book/tree/master/demo/chapter6
这里的示例代码你本地用 gulp 可以运行么？
如果一直不行可以尝试用[gulp-sass](https://github.com/dlmanning/gulp-sass) 编译速度更快，但支持的语法没有 ruby-sass 全。

**Comment by freedomdebug** [comment]
@nimojs 
和这个哥们一个情况，加了环境变量还是解决不了http://stackoverflow.com/questions/32853703/gulp-ruby-sass-sass-is-not-recognized-as-an-internal-or-external-command-op

**Comment by nimojs** [comment]
```shell
sass -v
Sass 3.4.8 (Selective Steve)
```
试试看sass是否安装成功

**Comment by freedomdebug** [comment]
![错误信息](http://chuantu.biz/t2/22/1450947351x-1376440132.jpg)

**Comment by freedomdebug** [comment]
@nimojs  帮忙看下

**Comment by freedomdebug** [comment]
@nimojs  
3q，重装了ruby正常了

**Comment by lroronoazoro** [comment]
我想问一下,是否有关于Iconfont的东西, 例如, 把所有字体独立出来, 写成class, 最后, 通过gulp把需要的字体打包到一起

**Comment by nimojs** [comment]
@lroronoazoro 
这个我一直没这样用过，我是用 http://iconfont.cn/ 的在线服务，选择字体直接服务器打包成全兼容的字体文件和CSS的。

建议看看这个 [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont)

**Comment by guohuihot** [comment]
Iconfont 可以把svg打包生成字体文件，同时生成scss,用时直接导进来就行，这样就好维护了

**Comment by hentaicreep** [comment]
我想了解下有没有一个插件，可以做到与gradle的buildtype类似的效果，就是debug时使用foo.debug.js，release时使用foo.release.js

**Comment by nimojs** [comment]
@hentaicreep 

https://github.com/zswang/jdists
https://github.com/zswang/gulp-jdists

```js
/*<online>*/
压缩版本代码
/*</online>*/
未压缩版本代码
/*<dev>*/
/*</dev>*/
```

**Comment by hentaicreep** [comment]
@nimojs 非常感谢，我去研究一下~
